import FeaturedPosts from '@/components/home-page/FeaturedPosts'
import Hero from '@/components/home-page/Hero'
import { getFeaturedPosts } from '@/lib/posts-util';
import Head from 'next/head'
import { Fragment, useEffect } from 'react';

export async function getAllDocuments(){
  const client = await MongoClient.connect('mongodb+srv://neoDitjoe:QzxbcXjqmbsSGq8E@cluster0.epmyjys.mongodb.net/profile?retryWrites=true&w=majority')
      const db = client.db()
      const documents = await db
          .collection('profiledata')
          .find()
          .sort(sort)
          .toArray()
      // return documents
  }

  // console.log(documents)

export default function Home(props) {

  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <FeaturedPosts posts={props.posts}/>
      </main>
    </Fragment>
  )
}


export function getStaticProps(){
  const featuredPosts = getFeaturedPosts()

  return {
    props: {
      posts : featuredPosts
    }
  }
}