import FeaturedPosts from '@/components/home-page/FeaturedPosts'
import Hero from '@/components/home-page/Hero'
import Head from 'next/head'
import { Fragment } from 'react'

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <FeaturedPosts />
      </main>
    </Fragment>
  )
}
